moving async-content-test from legacy tests to the basic app
ember-fastboot/ember-cli-fastboot pull request #793
Opened 2020-09-24 04:20 UTC by kiwiupover

remove legacy test

2020-09-24 04:21 UTC, kiwiupover commented
@rwjblue can you review this please

2020-09-24 14:39 UTC, rwjblue commented on test-packages/basic-app/app/components/async-content.js
> +// });
Should be deleted or incorporated

2020-09-24 15:28 UTC, rwjblue requested changes

2020-09-24 15:28 UTC, rwjblue commented on test-packages/basic-app/test/async-content-test.js
> +    console.log('body', response.body);
Probably don't need to keep this

2020-09-25 14:30 UTC, kiwiupover commented
@rwjblue I'm sorry I sent this over when it was not ready

It is ready now.

2020-09-25 15:16 UTC, rwjblue approved these changes

2020-09-25 15:16 UTC, merged